name: raqs_jan
description: Cultural Iranian music player with dancing visualizers - by cjhabib
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  just_audio: ^0.9.40
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
